version: '2'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./infra/mongodb/data:/data/db
    networks:
      - reactive-network
    command: mongod --smallfiles
#    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo:
    image: reactive/mongo-data-service:0.1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_AUTHENTICATION_DATABASE=admin
    networks:
      - reactive-network
    links:
      - mongodb
    depends_on:
      - mongodb

  stream:
    image: reactive/stream-service:0.1.0-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - reactive-network

  app:
    image: reactive/ui-app:0.1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_API_URL=http://mongo:8080
      - STREAM_API_URL=http://stream:8080
    networks:
      - reactive-network
    links:
      - mongo
      - stream
    depends_on:
      - mongo
      - stream

networks:
  reactive-network:
    driver: bridge
