server:
  port: ${PORT:8081}
#logging:
#  level:
#    root: debug
#    org.springframework.web.reactive.function: INFO
#    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
#    org.springframework.data.mongodb.core.query.Query: DEBUG
endpoints:
  default:
    web:
      enabled: true
spring:
  application:
    name: mongo-data-service
  data:
    mongodb:
      repositories:
        enabled: false

---
spring:
  profiles: docker
  data:
    mongodb:
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
      grid-fs-database: images
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

---
spring:
  profiles: cloud
  data:
    mongodb:
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
      grid-fs-database: images
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
