server:
  port: ${PORT:8082}
#logging:
#  level:
#    root: debug
endpoints:
  default:
    web:
      enabled: true
spring:
  application:
    name: stream-service
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false

---
spring:
  profiles: docker

---
spring:
  profiles: cloud
